# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "shopper"
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - 3306:3306
    volumes:
      - ./databse:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: 12345
  #     POSTGRES_DB: eshopper
  #   volumes:
  #     - ./mydb:/var/lib/postgresql
  #   restart: always