"""initial4

Revision ID: 182391a96cba
Revises: a408ef612bbd
Create Date: 2022-09-28 23:46:16.915467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182391a96cba'
down_revision = 'a408ef612bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discounted_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discounted_price')
    # ### end Alembic commands ###
