"""initial7

Revision ID: 279976961bbb
Revises: cee616b1d89e
Create Date: 2022-09-29 21:30:20.451907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279976961bbb'
down_revision = 'cee616b1d89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    # ### end Alembic commands ###
