"""initial9

Revision ID: 80e4e9e4f1f4
Revises: a0d6ff8a2623
Create Date: 2022-09-30 00:13:41.536701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e4e9e4f1f4'
down_revision = 'a0d6ff8a2623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'favorite', ['product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='unique')
    # ### end Alembic commands ###
