"""initial5

Revision ID: a2bb711981bd
Revises: 182391a96cba
Create Date: 2022-09-28 23:47:32.308981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2bb711981bd'
down_revision = '182391a96cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'discounted_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'discounted_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
